### PR TITLE
Rebased aura-pos onto the current stable v2.2.9

### PR DESCRIPTION
**Pull request by vkomenda**

### CODE REVIEW

**Comment by afck** [comment]
I'm fine with it if the others are. (But you'll probably have to force-push instead of using any of GitHub's merge options?)

**Comment by vkomenda** [comment]
It's tempting just to hit the green "merge" button. I wonder how this would work too.

**Comment by phahulin** [comment]
I wonder, were there any serious conflicts during rebase?

**Comment by vkomenda** [comment]
@phahulin, I was surprised to find there weren't any conflicts.
@afck, maybe we can use the "rebase and merge" option. Although this would be the second rebase, hopefully trivial since there are no new commits, and the first rebase went with no conflicts.

**Comment by afck** [comment]
> maybe we can use the "rebase and merge" option

I don't think so: That would rebase the wrong way round, wouldn't it? Putting the 2.2.9 commits on top of our own changes?
Also, it would be nice if we could merge #92 first…

**Comment by vkomenda** [comment]
@afck, I agree with you. If we rebase on top of `aura-pos`, then our commits will be at the bottom. The upstream commits will be at the top. We might want them to be the other way round. It doesn't mean much apart from that ordering because commits don't intersect.

**Pull request merged**
