### PR TITLE
Skip tests that currently fail

### PR DESCRIPTION
**Pull request by DemiMarie**
by marking them with `#[cfg(any())]`.

### CODE REVIEW

**Comment by vkomenda** [comment]
I fixed the test in `contract.rs`. Will PR tomorrow.

**Comment by DemiMarie** [comment]
@vkomenda ping

**Comment by vkomenda** [comment]
The first fix is in #106.

**Comment by DemiMarie** [comment]
@vkomenda can the other tests be fixed, or will they need to remain disabled?

**Comment by vkomenda** [comment]
@DemiMarie, I believe they can be fixed as well and we won't need to disable them.

**Comment by afck** [comment]
You could mark them `#[ignore]` instead of `#[cfg(any())]`.

**Comment by varasev** [comment]
@afck @vkomenda Could we close this PR? Seems we don't have failed unit tests anymore.

**Comment by varasev** [comment]
Maybe let's also remove the related `skip-failing-tests` branch?

**Pull request closed without merging**
