### PR TITLE
Rebase on Parity stable

### PR DESCRIPTION
**Pull request by DemiMarie**
If this passes review, I will force-push to the current `aura-pos` branch.

### CODE REVIEW

**Comment by vkomenda** [comment]
`aura-pos-backup` was an older branch. Probably that's why there are so many conflicts now.

Can you instead make a new branch off `aura-pos` and rebase it onto `stable`?

**Comment by DemiMarie** [comment]
@vkomenda I resolved the conflicts while rebasing.  Every commit (from Parity’s `stable` branch to HEAD) in this rebase builds.

**Comment by vkomenda** [comment]
@DemiMarie, I understand. What I meant was rather that v2.2.11 and v2.3.5 conflict with each other at the moment. Can we wait a bit with the rebase to see if the releases get linearized by the Parity team?

**Comment by DemiMarie** [comment]
@vkomenda Sure

**Comment by varasev** [comment]
This PR also could be closed, I guess (with deletion of the `aura-pos-backup` branch).

**Pull request closed without merging**
