### PR TITLE
Updated validator_set_aura ABI

### PR DESCRIPTION
**Pull request by vkomenda**
Synched to https://github.com/poanetwork/posdao-contracts/commit/072ffe281e22f34b78216811c37b90d2115e80d3

### CODE REVIEW

**Comment by afck** [comment]
The different formatting makes it hard to see the difference. I guess it's just the current `posdao-contracts`?
I wonder whether it would be better to just reduce this to only the part of the ABI that we're actually using.

**Comment by DemiMarie** [comment]
@afck I think we should instead write a script that generates the ABI files.  I wrote a simple Python script.

**Comment by vkomenda** [comment]
@DemiMarie, I took the `abi` section from the compiled `build/contracts/ValidatorSetAuRa.json` in `posdao-contracts`. I agree with @afck that this is too much and I have to go through Parity and list only those methods that are called from there.

**Comment by vkomenda** [comment]
> I wrote a simple Python script.

@DemiMarie, I don't see your script. Trying to guess the idea... Parse calls to `validator_set_aura` in `ethcore/src/engines/validator_set/safe_contract.rs` and filter the compiled ABI down to this result?

**Comment by vkomenda** [comment]
I didn't use a script for that but I filtered out only the functions and the event that are referred to in `validator_safe_contract.rs`.

Let me know if you want a script.

**Pull request merged**
