### PR TITLE
Fixes the failing validator contract test

### PR DESCRIPTION
**Pull request by vkomenda**
This is a fix for one out of three tests that fail in #93.

### CODE REVIEW

**Comment by vkomenda** [comment]
@DemiMarie, what kind of test? Bytecode generation in `test.sh` and substitution of that bytecode for a placeholder value of the address 5 constructor? A difficulty here is that `test.sh` does not assume an installed Solidity compiler.

I'd leave the bytecode unverified, with the Solidity file included for reference purposes. It's a step up with respect to the previous situation where the source file was missing altogether.

**Comment by DemiMarie** [comment]
@vkomenda A test that, if its dependencies are present, checks that the contract bytecode is correct.  Obviously, this would not run by default.

That said, this can wait.

**Comment by vkomenda** [comment]
@DemiMarie, since to check the bytecode we need to generate it anyway, I can include a script that generates the bytecode and another that checks the bytecode in the JSON file. Instead of checking the script might write the bytecode in the JSON file. That's a bit more practical.

**Comment by DemiMarie** [comment]
@vkomenda this still fails for me.  That said, the failure happens later, so it is still an improvement.  Merging.

**Pull request closed without merging**
